# Streamlit Configuration - Production (Railway)
# Optimized for cloud deployment

[server]
# Let Railway assign the port dynamically
headless = true
runOnSave = false
allowRunOnSave = false
maxUploadSize = 200  # Max file size in MB for CSV/Excel uploads
enableCORS = false
enableXsrfProtection = true

[browser]
# Production browser settings
gatherUsageStats = false

[client]
# Client settings
showErrorDetails = false

[runner]
# Runner settings
magicEnabled = true
postScriptGC = true
fastReruns = false

[logger]
# Logging settings
level = "warning"

# Theme settings
[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"